//x86_64-w64-mingw32-gcc EXIFLOADER-DLL-LIB.c -fdeclspec -lexif -Wall -Werror

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libexif/exif-data.h>

#define BUFFER_SIZE 4096

__declspec(dllexport) char* get_exif_json(const char* filename) {
    ExifData* exif_data = exif_data_new_from_file(filename);
    if (!exif_data) return NULL;

    char* json_result = NULL;
    int ai_flag = 0;
    char metadata_buffer[BUFFER_SIZE] = {0};
    size_t metadata_len = 0;

    // Перебор всех EXIF-тегов
    for (int ifd = 0; ifd < EXIF_IFD_COUNT; ifd++) {
        ExifContent* content = exif_data->ifd[ifd];
        if (!content) continue;

        for (unsigned int i = 0; i < content->count; i++) {
            ExifEntry* entry = content->entries[i];
            char value[1024];
            exif_entry_get_value(entry, value, sizeof(value));

            // Проверка на теги, связанные с AI
            if (strstr(value, "AI") || strstr(value, "Generated by AI")) {
                ai_flag = 1;
            }

            // Формирование строки метаданных
            const char* tag_name = exif_tag_get_name(entry->tag);
            char tag_str[128];
            if (!tag_name) {
                snprintf(tag_str, sizeof(tag_str), "Unknown(0x%04X)", entry->tag);
            } else {
                snprintf(tag_str, sizeof(tag_str), "%s", tag_name);
            }

            // Добавление к буферу
            int written = snprintf(
                metadata_buffer + metadata_len,
                BUFFER_SIZE - metadata_len,
                "%s: %s; ",
                tag_str,
                value
            );
            if (written > 0) metadata_len += written;
        }
    }

    // Удаление последнего "; "
    if (metadata_len >= 2) {
        metadata_buffer[metadata_len - 2] = '\0';
    }


    if (metadata_len > 0) {
        const char* json_template = 
            "{\"%s\": {"
                "\"AI\": %s,"
                "\"Other_metadata\": \"%s\""
            "}}";
        json_result = malloc(strlen(json_template) + strlen(filename) + metadata_len + 10);
        sprintf(
            json_result,
            json_template,
            filename,
            ai_flag ? "true" : "false",
            metadata_buffer
        );
    }

    exif_data_unref(exif_data);
    return json_result;
}

/*
int main(int argc, char** argv) {
    if (argc < 2) {
        printf("Usage: %s <filename>\n", argv[0]);
        return 1;
    }

    char* json = get_exif_json(argv[1]);
    if (json) {
        printf("%s\n", json);
        free(json);
    }
    return 0;
}
*/
