// This scr will parse EXIF img metadata and write it to JSON
// Почему я это делаю с помощью Си, а не обычного языка? Да хуй его знает.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libexif/exif-data.h>
#include <cJSON.h>

char* get_exif_json(const char* filename) {
    ExifData* exif_data = exif_data_new_from_file(filename);
    if (!exif_data) return NULL;

    cJSON *root = cJSON_CreateObject();
    cJSON *file_obj = cJSON_CreateObject();
    cJSON_AddItemToObject(root, filename, file_obj);

    int ai_flag = 0;
    cJSON *other_metadata = cJSON_CreateObject();
    cJSON_AddItemToObject(file_obj, "Other_metadata", other_metadata);

    for (int ifd = 0; ifd < EXIF_IFD_COUNT; ifd++) {
        ExifContent* content = exif_data->ifd[ifd];
        if (!content) continue;

        for (unsigned int i = 0; i < content->count; i++) {
            ExifEntry* entry = content->entries[i];
            char value[1024];
            exif_entry_get_value(entry, value, sizeof(value));

            if (strstr(value, "AI") || strstr(value, "Generated by AI")) {
                ai_flag = 1;
            }

            const char* tag_name = exif_tag_get_name(entry->tag);
            char tag_str[128];
            snprintf(tag_str, sizeof(tag_str), "%s",
                tag_name ? tag_name : "Unknown(0x%04X)", entry->tag);

            cJSON_AddStringToObject(other_metadata, tag_str, value);
        }
    }

    cJSON_AddBoolToObject(file_obj, "AI", ai_flag);
    char* json_result = cJSON_Print(root);
    
    cJSON_Delete(root);
    exif_data_unref(exif_data);
    return json_result;
}

/*
int main(int argc, char** argv) {
    if (argc < 2) {
        printf("Usage: %s <filename>\n", argv[0]);
        return 1;
    }

    char* json = get_exif_json(argv[1]);
    if (json) {
        printf("%s\n", json);
        free(json);
    }
    return 0;
}
*/

 
// Не обращайте внимания на комментарии просто я бездарь и ИИ чинила мой код, а удалять их мне лень. 
// Ну кароче если этот скриптик в жсон нихуя не возвращает то другие не будут запускаться, пока графики нет и 
// я не успел костылизировать решение. 
